# Generated by Django 3.2.10 on 2024-01-28 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='resume',
            field=models.FileField(null=True, upload_to='resumes/'),
        ),
    ]
