# Generated by Django 3.2.10 on 2024-01-29 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0002_alter_userprofile_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='resume',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
