# Generated by Django 3.2.10 on 2024-02-20 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0003_alter_userprofile_resume'),
    ]

    operations = [
    ]
