# Generated by Django 3.2.10 on 2024-03-09 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0006_employerprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employerprofile',
            name='logo',
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='contactnumber',
            field=models.IntegerField(null=True),
        ),
    ]
