# Generated by Django 3.2.10 on 2024-03-09 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0007_auto_20240309_1906'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employerprofile',
            name='contactnumber',
        ),
    ]
