# Generated by Django 3.2.10 on 2024-02-22 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0002_candidatesapplied'),
    ]

    operations = [
    ]
